config/routes.rb
Rails.application.routes.draw do
  resources :students
  # resources :choose_electrical_subjects
  namespace :users do
    resources :sessions, :students_biographies, :choose_electrical_subjects
    get "login" => 'sessions#new', :as => "login"
    get "logout" => 'sessions#destroy', :as => "logout"
  end
  namespace :admin do
    resources :users, :sessions, :buku_induks, :lectures, :functional_structurals, :students_biographies, :civil_subjects, :electrical_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
    #  sessions
     get "istpisuper" => 'sessions#new', :as => "istpisuper"
     get "logout" => 'sessions#destroy', :as => "logout"

    #  calon_mahasiswa
     get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
     get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
     get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
     delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    #  dosen
     get 'dosen_index' => 'lectures#index', :as => "dosen_index"
     get 'dosen_index/new' => 'lectures#new', :as => "new_dosen"
     get 'dosen/:id/edit' => 'lectures#edit', :as => "edit_dosen"
     get 'dosen/:id' => 'lectures#show', :as => "dosen"
     delete 'dosen/:id' => 'lectures#destroy', :as => "delete_dosen"

     # struktural
     get 'struktural_index' => 'functional_structurals#index', :as => "struktural_index"
     get 'struktural_index/new' => 'functional_structurals#new', :as => "new_struktural"
     get 'struktural/:id/edit' => 'functional_structurals#edit', :as => "edit_struktural"
     get 'struktural/:id' => 'functional_structurals#show', :as => "struktural"
     delete 'struktural/:id' => 'functional_structurals#destroy', :as => "delete_struktural"

     #electricalshcedulesubject
     get 'download_sk_mengajar_sipil' => 'civilschedulesubjects#download_pdf', :as => "download_sk_mengajar_sipil"
     get 'download_sk_mengajar_elektro' => 'electricalschedulesubjects#download_pdf', :as => "download_sk_mengajar_elektro"

       #  surat masuk
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

       #  surat keluar
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    resources :registrations do
       collection do
         get 'ok' => 'registrations#ok_mahasiswa', :as => "ok_mahasiswa"
       end
    end


  end

  resources :incoming_mails, :outcoming_mails, :students_biographies, :buku_induks, :functional_structurals, :lectures, :registrations, :electrical_subjects, :civil_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
  #registrations
  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
  get 'calon_mahasiswa/:id/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
  get 'calon_mahasiswa/:id' => 'registrations#show', :as => "calon_mahasiswa"
  delete 'calon_mahasiswa/:id' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

  #lectures
  get 'dosen' => 'lectures#index', :as => "dosen"

  #surat masuk
  get 'surat_masuk_index' => 'incoming_mails#index', :as => "surat_masuk_index"

  #kurikulum Teknik Elektro
  resources :electrical_subjects do
    # collection do
    #   get  'download' => 'electrical_subjects#download', as: :download
    # end
  end
  #beranda
  root 'pages#index'
  get 'aturan_kuliah' => 'pages#aturan_kuliah', :as => 'aturan_kuliah'


  # users
  # resources :users do
  #   resources :choose_electrical_subjects
  # end

end

app/models/studiyear.rb
# == Schema Information
#
# Table name: studiyears
#
#  id         :integer          not null, primary key
#  name       :string
#  even_odd   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Studiyear < ActiveRecord::Base
  has_many :choose_electrical_subjects, dependent: :destroy
  has_many :electricalschedulesubjects, dependent: :destroy
  has_many :civilschedulesubjects, dependent: :destroy
end

app/controllers/admin/studiyears_controller.rb
class Admin::StudiyearsController < ApplicationController
  before_action :set_studiyear, only: [:show, :edit, :update, :destroy]

  # GET /studiyears
  # GET /studiyears.json
  def index
    @studiyears = Studiyear.all
  end

  # GET /studiyears/1
  # GET /studiyears/1.json
  def show
  end

  # GET /studiyears/new
  def new
    @studiyear = Studiyear.new
  end

  # GET /studiyears/1/edit
  def edit
  end

  # POST /studiyears
  # POST /studiyears.json
  def create
    @studiyear = Studiyear.new(studiyear_params)

    respond_to do |format|
      if @studiyear.save
        format.html { redirect_to admin_studiyears_path, notice: 'Tahun ajaran berhasil dibuat' }
        format.json { render :show, status: :created, location: @studiyear }
      else
        format.html { render :new }
        format.json { render json: @studiyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studiyears/1
  # PATCH/PUT /studiyears/1.json
  def update
    respond_to do |format|
      if @studiyear.update(studiyear_params)
        format.html { redirect_to admin_studiyears_path, notice: 'Tahun ajaran berhasil diperbarui' }
        format.json { render :show, status: :ok, location: @studiyear }
      else
        format.html { render :edit }
        format.json { render json: @studiyear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studiyears/1
  # DELETE /studiyears/1.json
  def destroy
    @studiyear.destroy
    respond_to do |format|
      format.html { redirect_to admin_studiyears_url, notice: 'Tahun ajaran berhasil dihapus' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studiyear
      @studiyear = Studiyear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studiyear_params
      params.require(:studiyear).permit(:name, :even_odd, :status)
    end
end

app/helpers/studiyears_helper.rb
module StudiyearsHelper
end

app/views/admin/studiyears/_form.html.erb
<%= simple_form_for([:admin, @studiyear]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label:'Tahun Ajaran', placeholder:'Misalnya 2000/2001' %>
    <%= f.input :even_odd, collection:['Ganjil', 'Genap'], label:'Ganjil atau Genap', include_blank: false %>
    <%= f.input :status, label: 'Status Aktif' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-success' %>&nbsp;&nbsp;<%= link_to 'Kembali', admin_studiyears_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/admin/studiyears/edit.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-sm-8 col-md-8'>
      <h3 class='lead'>Edit Tahun Ajaran</h3>

      <%= render 'form' %>


    </div>
  </div>
</div>

app/views/admin/studiyears/index.html.erb
<% if @studiyears.present? %>
<div class="well">
  <h1 class="lead">Daftar Tahun Ajar&nbsp;&nbsp;<%= link_to 'Buat Tahun Ajaran', new_admin_studiyear_path, class:'btn btn-default' %></h1>

  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Tahun Ajar</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @studiyears.each do |studiyear| %>
        <tr>
          <td><%= studiyear.name %>&nbsp;&nbsp;<%= studiyear.even_odd %>&nbsp;&nbsp;<%= 'Aktif' if studiyear.status == true %></td>
          <td><%= link_to 'Edit', edit_admin_studiyear_path(studiyear), class:'btn btn-warning' %>&nbsp;&nbsp;<%= link_to 'Hapus', admin_studiyear_path(studiyear), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
</div>

<% else %>
<h3 class="lead">Maaf Data Belum Ada, Silahkan Datang Kembali..&nbsp;&nbsp;<%= link_to 'Buat Tahun Ajaran', new_admin_studiyear_path, class:'btn btn-default' %></h3>
<% end %>

app/views/admin/studiyears/new.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-sm-8 col-md-8'>
      <h3 class='lead'>Buat Tahun Ajaran</h3>

      <%= render 'form' %>

      
    </div>
  </div>
</div>

app/views/admin/studiyears/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @studiyear.name %>&nbsp;&nbsp;<%= @studiyear.even_odd %>
</p>


<%= link_to 'Edit', edit_studiyear_path(@studiyear) %> |
<%= link_to 'Back', studiyears_path %>