config/routes.rb
Rails.application.routes.draw do
  resources :students
  # resources :choose_electrical_subjects
  namespace :users do
    resources :sessions, :students_biographies, :choose_electrical_subjects
    get "login" => 'sessions#new', :as => "login"
    get "logout" => 'sessions#destroy', :as => "logout"
  end
  namespace :admin do
    resources :users, :sessions, :buku_induks, :lectures, :functional_structurals, :students_biographies, :civil_subjects, :electrical_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
    #  sessions
     get "istpisuper" => 'sessions#new', :as => "istpisuper"
     get "logout" => 'sessions#destroy', :as => "logout"

    #  calon_mahasiswa
     get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
     get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
     get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
     delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    #  dosen
     get 'dosen_index' => 'lectures#index', :as => "dosen_index"
     get 'dosen_index/new' => 'lectures#new', :as => "new_dosen"
     get 'dosen/:id/edit' => 'lectures#edit', :as => "edit_dosen"
     get 'dosen/:id' => 'lectures#show', :as => "dosen"
     delete 'dosen/:id' => 'lectures#destroy', :as => "delete_dosen"

     # struktural
     get 'struktural_index' => 'functional_structurals#index', :as => "struktural_index"
     get 'struktural_index/new' => 'functional_structurals#new', :as => "new_struktural"
     get 'struktural/:id/edit' => 'functional_structurals#edit', :as => "edit_struktural"
     get 'struktural/:id' => 'functional_structurals#show', :as => "struktural"
     delete 'struktural/:id' => 'functional_structurals#destroy', :as => "delete_struktural"

     #electricalshcedulesubject
     get 'download_sk_mengajar_sipil' => 'civilschedulesubjects#download_pdf', :as => "download_sk_mengajar_sipil"
     get 'download_sk_mengajar_elektro' => 'electricalschedulesubjects#download_pdf', :as => "download_sk_mengajar_elektro"

       #  surat masuk
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

       #  surat keluar
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    resources :registrations do
       collection do
         get 'ok' => 'registrations#ok_mahasiswa', :as => "ok_mahasiswa"
       end
    end


  end

  resources :incoming_mails, :outcoming_mails, :students_biographies, :buku_induks, :functional_structurals, :lectures, :registrations, :electrical_subjects, :civil_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
  #registrations
  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
  get 'calon_mahasiswa/:id/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
  get 'calon_mahasiswa/:id' => 'registrations#show', :as => "calon_mahasiswa"
  delete 'calon_mahasiswa/:id' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

  #lectures
  get 'dosen' => 'lectures#index', :as => "dosen"

  #surat masuk
  get 'surat_masuk_index' => 'incoming_mails#index', :as => "surat_masuk_index"

  #kurikulum Teknik Elektro
  resources :electrical_subjects do
    # collection do
    #   get  'download' => 'electrical_subjects#download', as: :download
    # end
  end
  #beranda
  root 'pages#index'
  get 'aturan_kuliah' => 'pages#aturan_kuliah', :as => 'aturan_kuliah'


  # users
  # resources :users do
  #   resources :choose_electrical_subjects
  # end

end

app/models/students_biography.rb
# == Schema Information
#
# Table name: students_biographies
#
#  id                                   :integer          not null, primary key
#  full_name                            :string
#  stambuk                              :string
#  jenis_kelamin                        :string
#  tempat_lahir                         :string
#  tanggal_lahir                        :string
#  agama                                :string
#  alamat_rumah_rt                      :string
#  alamat_rumah_rw                      :string
#  alamat_rumah_kota                    :string
#  alamat_rumah_kabupaten               :string
#  alamat_rumah_kodepos                 :string
#  siswa_no_kontak                      :string
#  user_id                              :integer
#  ayah_nama                            :string
#  ayah_tempat_lahir                    :string
#  ayah_tanggal_lahir                   :string
#  ayah_no_kontak                       :string
#  ayah_alamat_rt                       :string
#  ayah_alamat_rw                       :string
#  ayah_alamat_kota                     :string
#  ayah_alamat_kabupaten                :string
#  ayah_alamat_kodepos                  :string
#  ayah_pendidikan_terakhir             :string
#  ayah_pekerjaan                       :string
#  ibu_nama                             :string
#  ibu_tempat_lahir                     :string
#  ibu_tanggal_lahir                    :string
#  ibu_no_kontak                        :string
#  ibu_alamat_rt                        :string
#  ibu_alamat_rw                        :string
#  ibu_alamat_kota                      :string
#  ibu_alamat_kabupaten                 :string
#  ibu_alamat_kodepos                   :string
#  ibu_pendidikan_terakhir              :string
#  ibu_pekerjaan                        :string
#  wali_nama                            :string
#  wali_tempat_lahir                    :string
#  wali_tanggal_lahir                   :string
#  wali_no_kontak                       :string
#  wali_alamat_rt                       :string
#  wali_alamat_rw                       :string
#  wali_alamat_kota                     :string
#  wali_alamat_kabupaten                :string
#  wali_alamat_kodepos                  :string
#  wali_pendidikan_terakhir             :string
#  wali_pekerjaan                       :string
#  fakultas                             :string
#  jurusan                              :string
#  sekolah_sd                           :string
#  sekolah_sd_tahun_lulus               :string
#  sekolah_smp_tahun_lulus              :string
#  sekolah_smu_tahun_lulus              :string
#  perguruan_tinggi_asal                :string
#  perguruan_tinggi_asal_tahun_terakhir :string
#  created_at                           :datetime         not null
#  updated_at                           :datetime         not null
#

class StudentsBiography < ActiveRecord::Base
  belongs_to :user
  # before_create :set_stambuk
  def self.search(query)
    #code
    where("lower(name) LIKE lower(?) OR lower(stambuk) LIKE lower(?)", "%#{query}%", "%#{query}%")
  end

  # def set_stambuk
  #   #code
  #   # format stambuk : tahun(216)+kode jurusan(sipil 11 elektro 12)+1+no urut
  #   self.stambuk = '#{tahun_stambuk}+#{kode_jurusan}+#{no_urut}'
  # end

  def tahun_stambuk
    #code

  end

  def kode_jurusan
    #code
  end

  def no_urut
    #code
  end
end

app/controllers/admin/students_biographies_controller.rb
class Admin::StudentsBiographiesController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :set_students_biography, only: [:show, :edit, :update, :destroy]

  # GET /students_biographies
  # GET /students_biographies.json
  def index
    if params[:search]
        @students_biographies = StudentsBiography.paginate(:page => params[:page], per_page: 10).search(params[:search]).order('stambuk asc')
    else
        @students_biographies = StudentsBiography.all.paginate(:page => params[:page], per_page: 10).order('stambuk asc')
    end
  end

  # GET /students_biographies/1
  # GET /students_biographies/1.json
  def show
  end

  # GET /students_biographies/new
  def new
    @students_biography = StudentsBiography.new
  end

  # GET /students_biographies/1/edit
  def edit
  end

  # POST /students_biographies
  # POST /students_biographies.json
  def create
    @students_biography = StudentsBiography.new(students_biography_params)

    respond_to do |format|
      if @students_biography.save
        format.html { redirect_to admin_students_biographies_path, notice: 'Students biography was successfully created.' }
        format.json { render :show, status: :created, location: @students_biography }
      else
        format.html { render :new }
        format.json { render json: @students_biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students_biographies/1
  # PATCH/PUT /students_biographies/1.json
  def update
    respond_to do |format|
      if @students_biography.update(students_biography_params)
        format.html { redirect_to admin_students_biographies_path, notice: 'Students biography was successfully updated.' }
        format.json { render :show, status: :ok, location: @students_biography }
      else
        format.html { render :edit }
        format.json { render json: @students_biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students_biographies/1
  # DELETE /students_biographies/1.json
  def destroy
    @students_biography.destroy
    respond_to do |format|
      format.html { redirect_to admin_students_biographies_url, notice: 'Students biography was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_biography
      @students_biography = StudentsBiography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def students_biography_params
      params.require(:students_biography).permit(:full_name, :stambuk, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :agama, :alamat_rumah_rt, :alamat_rumah_rw, :alamat_rumah_kota, :alamat_rumah_kabupaten, :alamat_rumah_kodepos, :siswa_no_kontak, :user_id, :ayah_nama, :ayah_tempat_lahir, :ayah_tanggal_lahir, :ayah_no_kontak, :ayah_alamat_rt, :ayah_alamat_rw, :ayah_alamat_kota, :ayah_alamat_kabupaten, :ayah_alamat_kodepos, :ayah_pendidikan_terakhir, :ayah_pekerjaan, :ibu_nama, :ibu_tempat_lahir, :ibu_tanggal_lahir, :ibu_no_kontak, :ibu_alamat_rt, :ibu_alamat_rw, :ibu_alamat_kota, :ibu_alamat_kabupaten, :ibu_alamat_kodepos, :ibu_pendidikan_terakhir, :ibu_pekerjaan, :wali_nama, :wali_tempat_lahir, :wali_tanggal_lahir, :wali_no_kontak, :wali_alamat_rt, :wali_alamat_rw, :wali_alamat_kota, :wali_alamat_kabupaten, :wali_alamat_kodepos, :wali_pendidikan_terakhir, :wali_pekerjaan, :fakultas, :jurusan, :sekolah_sd, :sekolah_sd_tahun_lulus, :sekolah_smp_tahun_lulus, :sekolah_smu_tahun_lulus, :perguruan_tinggi_asal, :perguruan_tinggi_asal_tahun_terakhir)
    end
end

app/controllers/students_biographies_controller.rb
class StudentsBiographiesController < ApplicationController
  before_action :set_students_biography, only: [:show, :edit, :update, :destroy]

  # GET /students_biographies
  # GET /students_biographies.json
  def index
    if params[:search]
        @students_biographies = StudentsBiography.paginate(:page => params[:page], per_page: 10).search(params[:search]).order('stambuk asc')
    else
        @students_biographies = StudentsBiography.all.paginate(:page => params[:page], per_page: 10).order('stambuk asc')
    end
  end

  # GET /students_biographies/1
  # GET /students_biographies/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_biography
      @students_biography = StudentsBiography.find(params[:id])
    end
end

app/controllers/user/students_biographies_controller.rb
class Users::StudentsBiographiesController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :set_students_biography, only: [:show, :edit, :update, :destroy]

  # GET /students_biographies
  # GET /students_biographies.json
  def index
    if params[:search]
        @students_biographies = StudentsBiography.paginate(:page => params[:page], per_page: 10).search(params[:search]).order('stambuk asc')
    else
        @students_biographies = StudentsBiography.all.paginate(:page => params[:page], per_page: 10).order('stambuk asc')
    end
  end

  # GET /students_biographies/1
  # GET /students_biographies/1.json
  def show
  end

  # GET /students_biographies/new
  def new
    @students_biography = StudentsBiography.new
  end

  # GET /students_biographies/1/edit
  def edit
  end

  # POST /students_biographies
  # POST /students_biographies.json
  def create
    @students_biography = StudentsBiography.new(students_biography_params)

    respond_to do |format|
      if @students_biography.save
        format.html { redirect_to admin_students_biographies_path, notice: 'Students biography was successfully created.' }
        format.json { render :show, status: :created, location: @students_biography }
      else
        format.html { render :new }
        format.json { render json: @students_biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students_biographies/1
  # PATCH/PUT /students_biographies/1.json
  def update
    respond_to do |format|
      if @students_biography.update(students_biography_params)
        format.html { redirect_to admin_students_biographies_path, notice: 'Students biography was successfully updated.' }
        format.json { render :show, status: :ok, location: @students_biography }
      else
        format.html { render :edit }
        format.json { render json: @students_biography.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students_biographies/1
  # DELETE /students_biographies/1.json
  def destroy
    @students_biography.destroy
    respond_to do |format|
      format.html { redirect_to admin_students_biographies_url, notice: 'Students biography was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_biography
      @students_biography = StudentsBiography.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def students_biography_params
      params.require(:students_biography).permit(:full_name, :stambuk, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :agama, :alamat_rumah_rt, :alamat_rumah_rw, :alamat_rumah_kota, :alamat_rumah_kabupaten, :alamat_rumah_kodepos, :siswa_no_kontak, :user_id, :ayah_nama, :ayah_tempat_lahir, :ayah_tanggal_lahir, :ayah_no_kontak, :ayah_alamat_rt, :ayah_alamat_rw, :ayah_alamat_kota, :ayah_alamat_kabupaten, :ayah_alamat_kodepos, :ayah_pendidikan_terakhir, :ayah_pekerjaan, :ibu_nama, :ibu_tempat_lahir, :ibu_tanggal_lahir, :ibu_no_kontak, :ibu_alamat_rt, :ibu_alamat_rw, :ibu_alamat_kota, :ibu_alamat_kabupaten, :ibu_alamat_kodepos, :ibu_pendidikan_terakhir, :ibu_pekerjaan, :wali_nama, :wali_tempat_lahir, :wali_tanggal_lahir, :wali_no_kontak, :wali_alamat_rt, :wali_alamat_rw, :wali_alamat_kota, :wali_alamat_kabupaten, :wali_alamat_kodepos, :wali_pendidikan_terakhir, :wali_pekerjaan, :fakultas, :jurusan, :sekolah_sd, :sekolah_sd_tahun_lulus, :sekolah_smp_tahun_lulus, :sekolah_smu_tahun_lulus, :perguruan_tinggi_asal, :perguruan_tinggi_asal_tahun_terakhir)
    end
end

app/controllers/users/students_biographies_controller.rb
class Users::StudentsBiographiesController < ApplicationController
  before_action :set_students_biography, only: [:show, :edit, :update, :destroy]

  # GET /students_biographies
  # GET /students_biographies.json
  def index
    if params[:search]
        @students_biographies = StudentsBiography.paginate(:page => params[:page], per_page: 10).search(params[:search]).order('stambuk asc')
    else
        @students_biographies = StudentsBiography.all.paginate(:page => params[:page], per_page: 10).order('stambuk asc')
    end
  end

  # GET /students_biographies/1
  # GET /students_biographies/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_students_biography
      @students_biography = StudentsBiography.find(params[:id])
    end
end

app/helpers/students_biographies_helper.rb
module StudentsBiographiesHelper
end

app/views/students_biographies/index.html.erb
<% if @students_biographies.present? %>
<h3 class="lead">Daftar Nama Mahasiswa ISTPI Aktif</h3>
<div class="panel panel-default">
  <div class="panel-title pull-right">
    <%= render 'shared/search' %>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Nama</th>
          <th>Stambuk</th>
          <th>Jenis kelamin</th>
          <th>Tempat, Tanggal Lahir</th>
          <th>Fakultas</th>
          <th>Jurusan</th>
        </tr>
      </thead>

      <tbody>
        <% @students_biographies.each do |students_biography| %>
          <tr>
            <td><%= link_to students_biography.user.name, students_biography rescue nil %></td>
            <td><%= students_biography.stambuk %></td>
            <td><%= students_biography.jenis_kelamin %></td>
            <td><%= students_biography.tempat_lahir %>&nbsp; <%= students_biography.tanggal_lahir %></td>
            <td><%= students_biography.fakultas %></td>
            <td><%= students_biography.jurusan %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

      <%= will_paginate @students_biographies, :previous_label => '&laquo;', :next_label => '&raquo;', renderer: BootstrapPagination::Rails %>

<br>
<% else %>
<h3 class="lead">Maaf, Belum Ada Data Mahasiswa Silahkan Kembali Lain Waktu..</h3>
<% end %>
  </div>
</div>

app/views/students_biographies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @students_biography.full_name %>
</p>

<p>
  <strong>Stambuk:</strong>
  <%= @students_biography.stambuk %>
</p>

<p>
  <strong>Jenis kelamin:</strong>
  <%= @students_biography.jenis_kelamin %>
</p>

<p>
  <strong>Tempat lahir:</strong>
  <%= @students_biography.tempat_lahir %>
</p>

<p>
  <strong>Tanggal lahir:</strong>
  <%= @students_biography.tanggal_lahir %>
</p>

<p>
  <strong>Agama:</strong>
  <%= @students_biography.agama %>
</p>

<p>
  <strong>Alamat rumah rt:</strong>
  <%= @students_biography.alamat_rumah_rt %>
</p>

<p>
  <strong>Alamat rumah rw:</strong>
  <%= @students_biography.alamat_rumah_rw %>
</p>

<p>
  <strong>Alamat rumah kota:</strong>
  <%= @students_biography.alamat_rumah_kota %>
</p>

<p>
  <strong>Alamat rumah kabupaten:</strong>
  <%= @students_biography.alamat_rumah_kabupaten %>
</p>

<p>
  <strong>Alamat rumah kodepos:</strong>
  <%= @students_biography.alamat_rumah_kodepos %>
</p>

<p>
  <strong>Siswa no kontak:</strong>
  <%= @students_biography.siswa_no_kontak %>
</p>

<p>
  <strong>Ayah nama:</strong>
  <%= @students_biography.ayah_nama %>
</p>

<p>
  <strong>Ayah tempat lahir:</strong>
  <%= @students_biography.ayah_tempat_lahir %>
</p>

<p>
  <strong>Ayah tanggal lahir:</strong>
  <%= @students_biography.ayah_tanggal_lahir %>
</p>

<p>
  <strong>Ayah no kontak:</strong>
  <%= @students_biography.ayah_no_kontak %>
</p>

<p>
  <strong>Ayah alamat rt:</strong>
  <%= @students_biography.ayah_alamat_rt %>
</p>

<p>
  <strong>Ayah alamat rw:</strong>
  <%= @students_biography.ayah_alamat_rw %>
</p>

<p>
  <strong>Ayah alamat kota:</strong>
  <%= @students_biography.ayah_alamat_kota %>
</p>

<p>
  <strong>Ayah alamat kabupaten:</strong>
  <%= @students_biography.ayah_alamat_kabupaten %>
</p>

<p>
  <strong>Ayah alamat kodepos:</strong>
  <%= @students_biography.ayah_alamat_kodepos %>
</p>

<p>
  <strong>Ayah pendidikan terakhir:</strong>
  <%= @students_biography.ayah_pendidikan_terakhir %>
</p>

<p>
  <strong>Ayah pekerjaan:</strong>
  <%= @students_biography.ayah_pekerjaan %>
</p>

<p>
  <strong>Ibu nama:</strong>
  <%= @students_biography.ibu_nama %>
</p>

<p>
  <strong>Ibu tempat lahir:</strong>
  <%= @students_biography.ibu_tempat_lahir %>
</p>

<p>
  <strong>Ibu tanggal lahir:</strong>
  <%= @students_biography.ibu_tanggal_lahir %>
</p>

<p>
  <strong>Ibu no kontak:</strong>
  <%= @students_biography.ibu_no_kontak %>
</p>

<p>
  <strong>Ibu alamat rt:</strong>
  <%= @students_biography.ibu_alamat_rt %>
</p>

<p>
  <strong>Ibu alamat rw:</strong>
  <%= @students_biography.ibu_alamat_rw %>
</p>

<p>
  <strong>Ibu alamat kota:</strong>
  <%= @students_biography.ibu_alamat_kota %>
</p>

<p>
  <strong>Ibu alamat kabupaten:</strong>
  <%= @students_biography.ibu_alamat_kabupaten %>
</p>

<p>
  <strong>Ibu alamat kodepos:</strong>
  <%= @students_biography.ibu_alamat_kodepos %>
</p>

<p>
  <strong>Ibu pendidikan terakhir:</strong>
  <%= @students_biography.ibu_pendidikan_terakhir %>
</p>

<p>
  <strong>Ibu pekerjaan:</strong>
  <%= @students_biography.ibu_pekerjaan %>
</p>

<p>
  <strong>Wali nama:</strong>
  <%= @students_biography.wali_nama %>
</p>

<p>
  <strong>Wali tempat lahir:</strong>
  <%= @students_biography.wali_tempat_lahir %>
</p>

<p>
  <strong>Wali tanggal lahir:</strong>
  <%= @students_biography.wali_tanggal_lahir %>
</p>

<p>
  <strong>Wali no kontak:</strong>
  <%= @students_biography.wali_no_kontak %>
</p>

<p>
  <strong>Wali alamat rt:</strong>
  <%= @students_biography.wali_alamat_rt %>
</p>

<p>
  <strong>Wali alamat rw:</strong>
  <%= @students_biography.wali_alamat_rw %>
</p>

<p>
  <strong>Wali alamat kota:</strong>
  <%= @students_biography.wali_alamat_kota %>
</p>

<p>
  <strong>Wali alamat kabupaten:</strong>
  <%= @students_biography.wali_alamat_kabupaten %>
</p>

<p>
  <strong>Wali alamat kodepos:</strong>
  <%= @students_biography.wali_alamat_kodepos %>
</p>

<p>
  <strong>Wali pendidikan terakhir:</strong>
  <%= @students_biography.wali_pendidikan_terakhir %>
</p>

<p>
  <strong>Wali pekerjaan:</strong>
  <%= @students_biography.wali_pekerjaan %>
</p>

<p>
  <strong>Fakultas:</strong>
  <%= @students_biography.fakultas %>
</p>

<p>
  <strong>Jurusan:</strong>
  <%= @students_biography.jurusan %>
</p>

<p>
  <strong>Sekolah sd:</strong>
  <%= @students_biography.sekolah_sd %>
</p>

<p>
  <strong>Sekolah sd tahun lulus:</strong>
  <%= @students_biography.sekolah_sd_tahun_lulus %>
</p>

<p>
  <strong>Sekolah smp tahun lulus:</strong>
  <%= @students_biography.sekolah_smp_tahun_lulus %>
</p>

<p>
  <strong>Sekolah smu tahun lulus:</strong>
  <%= @students_biography.sekolah_smu_tahun_lulus %>
</p>

<p>
  <strong>Perguruan tinggi asal:</strong>
  <%= @students_biography.perguruan_tinggi_asal %>
</p>

<p>
  <strong>Perguruan tinggi asal tahun terakhir:</strong>
  <%= @students_biography.perguruan_tinggi_asal_tahun_terakhir %>
</p>

<%= link_to 'Edit', edit_students_biography_path(@students_biography) %> |
<%= link_to 'Back', students_biographies_path %>