config/routes.rb
Rails.application.routes.draw do
  resources :students
  # resources :choose_electrical_subjects
  namespace :users do
    resources :sessions, :students_biographies, :choose_electrical_subjects
    get "login" => 'sessions#new', :as => "login"
    get "logout" => 'sessions#destroy', :as => "logout"
  end
  namespace :admin do
    resources :users, :sessions, :buku_induks, :lectures, :functional_structurals, :students_biographies, :civil_subjects, :electrical_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
    #  sessions
     get "istpisuper" => 'sessions#new', :as => "istpisuper"
     get "logout" => 'sessions#destroy', :as => "logout"

    #  calon_mahasiswa
     get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
     get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
     get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
     delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    #  dosen
     get 'dosen_index' => 'lectures#index', :as => "dosen_index"
     get 'dosen_index/new' => 'lectures#new', :as => "new_dosen"
     get 'dosen/:id/edit' => 'lectures#edit', :as => "edit_dosen"
     get 'dosen/:id' => 'lectures#show', :as => "dosen"
     delete 'dosen/:id' => 'lectures#destroy', :as => "delete_dosen"

     # struktural
     get 'struktural_index' => 'functional_structurals#index', :as => "struktural_index"
     get 'struktural_index/new' => 'functional_structurals#new', :as => "new_struktural"
     get 'struktural/:id/edit' => 'functional_structurals#edit', :as => "edit_struktural"
     get 'struktural/:id' => 'functional_structurals#show', :as => "struktural"
     delete 'struktural/:id' => 'functional_structurals#destroy', :as => "delete_struktural"

     #electricalshcedulesubject
     get 'download_sk_mengajar_sipil' => 'civilschedulesubjects#download_pdf', :as => "download_sk_mengajar_sipil"
     get 'download_sk_mengajar_elektro' => 'electricalschedulesubjects#download_pdf', :as => "download_sk_mengajar_elektro"

       #  surat masuk
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

       #  surat keluar
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    resources :registrations do
       collection do
         get 'ok' => 'registrations#ok_mahasiswa', :as => "ok_mahasiswa"
       end
    end


  end

  resources :incoming_mails, :outcoming_mails, :students_biographies, :buku_induks, :functional_structurals, :lectures, :registrations, :electrical_subjects, :civil_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
  #registrations
  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
  get 'calon_mahasiswa/:id/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
  get 'calon_mahasiswa/:id' => 'registrations#show', :as => "calon_mahasiswa"
  delete 'calon_mahasiswa/:id' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

  #lectures
  get 'dosen' => 'lectures#index', :as => "dosen"

  #surat masuk
  get 'surat_masuk_index' => 'incoming_mails#index', :as => "surat_masuk_index"

  #kurikulum Teknik Elektro
  resources :electrical_subjects do
    # collection do
    #   get  'download' => 'electrical_subjects#download', as: :download
    # end
  end
  #beranda
  root 'pages#index'
  get 'aturan_kuliah' => 'pages#aturan_kuliah', :as => 'aturan_kuliah'


  # users
  # resources :users do
  #   resources :choose_electrical_subjects
  # end

end

app/views/shared/_aturan_kuliah.html.erb
<h3 class="lead">Aturan Perkuliahan</h3>
<ul>
  <li>Mahasiswa Tidak Diperkenankan Keluar Masuk Saat Perkuliahan Sedang Berlangsung</li>
  <li>Mahasiswa Tidak Boleh Makan Dan Minum Saat Perkuliahan Sedang Berlangsung</li>
  <li>Mahasiswa Tidak Boleh Memakai Sandal Jepit Dan Baju Kaos Pada Saat Perkuliahan Sedang Berlangsung</li>
  <li>Mahasiswa Tidak Boleh Gondrong</li>
</ul>

app/views/shared/_navigation.html.erb
<% unless current_user.present? %>
<!-- Navigasi Tanpa Login -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#"></a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= params[:controller]== 'pages' && params[:action]== 'index' ? 'active' : '' %>"><%= link_to "Beranda", root_url %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Akademik <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <li class="<%= params[:controller]== 'students_biographies' ? 'active' : '' %>"><%= link_to "Mahasiswa", students_biographies_path %></li>
            <li><%= link_to "Dosen", dosen_path %></li>
            <li><%= link_to "Penasehat Akademik", "#" %></li>
            <li ><%= link_to "Kalender Akademik", '#' %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sipil<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%#= link_to "Aturan Kuliah", '#' %></li>
            <li ><%= link_to "Kurikulum", civil_subjects_path %></li>
            <li ><%= link_to "Jadwal Kuliah", civilschedulesubjects_path %></li>
            <li><%#= link_to "Nilai", "#" %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Elektro<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%#= link_to "Aturan Kuliah", '#' %></li>
            <li ><%= link_to "Kurikulum", electrical_subjects_path %></li>
            <li ><%= link_to "Jadwal Kuliah", electricalschedulesubjects_path %></li>
          </ul>
        </li>
        <li ><%= link_to "Perpustakaan", '#' %></li>
        <li class="<%= params[:controller] == 'registrations' ? 'active' : '' %>"><%= link_to "Calon Mahasiswa", calon_mahasiswa_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log in", users_login_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Akhir Navigasi Tanpa Login -->
<% else %>
<!-- Navigasi Dengan Login -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user.role == "superadmin" %>
      <%= link_to "Admin", admin_users_path, class: "navbar-brand" %>
      <% else %>
      <%= link_to "Admin", "#", class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% %w['students_biographies', 'lectures'] %>
        <li class="dropdown <%= params[:controller]== '#{%w}' ? 'active': '' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Akademik<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Aturan", "#" %></li>
            <li class="<%= params[:controller]== 'admin/students_biographies' ? 'active' : '' %>"><%= link_to "Mahasiswa", admin_students_biographies_path %></li>
            <li class="<%= params[:controller] == 'admin/lectures' ? 'active' : '' %>"><%= link_to "Dosen", admin_dosen_index_path %></li>
            <li><%= link_to "Penasehat Akademik", "#" %></li>
            <li ><%= link_to "Kalender Akademik", '#' %></li>
          </ul>
        </li>
        <li class="dropdown <%= params[:controller] ==  'nil' ? 'active' : '' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Biro Akademik<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="<%= params[:controller] == 'admin/registrations' ? 'active' : '' %>"><%= link_to "Calon Mahasiswa", admin_calon_mahasiswa_index_path %></li>
            <li ><%= link_to "Buku Induk", admin_buku_induks_path %></li>
            <li ><%= link_to "Tahun Ajaran", admin_studiyears_path %></li>
            <li ><%= link_to "Semester", admin_semesters_path %></li>
            <li ><%= link_to "Ruangan", admin_classrooms_path %></li>
            <li ><%= link_to "Waktu", admin_classtimes_path %></li>

          </ul>
        </li>
        <li class="dropdown <%= params[:controller] ==  'nil' ? 'active' : '' %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Biro Umum<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%= link_to "Program Kerja", '#' %></li>
            <li class="<%= params[:controller] == 'functional_structurals' ? 'active' : '' %>"><%= link_to "Struktural", admin_functional_structurals_path %></li>
            <li class="<%= params[:controller]== 'incomings' ? 'active' : '' %>"><%= link_to "Surat Masuk", surat_masuk_index_path %></li>
            <li class="<%= params[:controller]== 'outcomings' ? 'active' : '' %>"><%= link_to "Surat Keluar", outcoming_mails_path %></li>
            <li ><%= link_to "Keuangan", '#' %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sipil<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%#= link_to "Aturan Kuliah", '#' %></li>
            <li ><%= link_to "Kurikulum", admin_civil_subjects_path %></li>
            <li ><%= link_to "Jadwal Kuliah", admin_civilschedulesubjects_path %></li>

          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Elektro<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li ><%#= link_to "Aturan Kuliah", '#' %></li>
            <li ><%= link_to "Kurikulum", admin_electrical_subjects_path %></li>
            <li ><%= link_to "Jadwal Kuliah", admin_electricalschedulesubjects_path %></li>

          </ul>
        </li>
        <li ><%= link_to "Perpustakaan", '#' %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown <%= params[:controller] ==  'nil' ? 'active' : '' %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li ><%= link_to "Edit Profil", '#' %></li>
              <li ><%= link_to "Ganti Password", edit_admin_user_path(current_user) %></li>
              <li ><%#= link_to "Lihat KRS ku", admin_user_choose_electrical_subjects_path(current_user) %></li>
              <li><%#= link_to "Isi KRS", new_admin_user_choose_electrical_subject_path(current_user) %></li>
              <li ><%= link_to "Jadwal Kuliah ku", '#' %></li>
              <li ><%= link_to "Nilaiku", '#' %></li>

            </ul>
          </li>
          <li><%= link_to "Log out", admin_logout_path %></li>
        <% else %>
          <li><%= link_to "Log in", admin_login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Akhir Navigasi Dengan Login -->
<% end %>

app/views/shared/_search.html.erb
<% if params[:controller] == 'admin/users' %>
    <%= form_tag(admin_users_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'admin/registrations' %>
    <%= form_tag(admin_registrations_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'admin/buku_induks' %>
    <%= form_tag(admin_buku_induks_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'admin/lectures' %>
    <%= form_tag(admin_lectures_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'lectures' %>
    <%= form_tag(lectures_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'admin/functional_structurals' %>
    <%= form_tag(admin_functional_structurals_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'students_biographies' %>
    <%= form_tag(students_biographies_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>
<% elsif params[:controller] == 'admin/students_biographies' %>
    <%= form_tag(admin_students_biographies_path, method: "get", id: "search-form", class:"search-form") do %>
        <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Cari..", class:"form-control" %>
        </div>
        <%= submit_tag "Cari", name: nil, class: "btn btn-success" %>
    <% end %>

<% end %>