config/routes.rb
Rails.application.routes.draw do
  resources :students
  # resources :choose_electrical_subjects
  namespace :users do
    resources :sessions, :students_biographies, :choose_electrical_subjects
    get "login" => 'sessions#new', :as => "login"
    get "logout" => 'sessions#destroy', :as => "logout"
  end
  namespace :admin do
    resources :users, :sessions, :buku_induks, :lectures, :functional_structurals, :students_biographies, :civil_subjects, :electrical_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
    #  sessions
     get "istpisuper" => 'sessions#new', :as => "istpisuper"
     get "logout" => 'sessions#destroy', :as => "logout"

    #  calon_mahasiswa
     get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
     get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
     get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
     delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
     get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    #  dosen
     get 'dosen_index' => 'lectures#index', :as => "dosen_index"
     get 'dosen_index/new' => 'lectures#new', :as => "new_dosen"
     get 'dosen/:id/edit' => 'lectures#edit', :as => "edit_dosen"
     get 'dosen/:id' => 'lectures#show', :as => "dosen"
     delete 'dosen/:id' => 'lectures#destroy', :as => "delete_dosen"

     # struktural
     get 'struktural_index' => 'functional_structurals#index', :as => "struktural_index"
     get 'struktural_index/new' => 'functional_structurals#new', :as => "new_struktural"
     get 'struktural/:id/edit' => 'functional_structurals#edit', :as => "edit_struktural"
     get 'struktural/:id' => 'functional_structurals#show', :as => "struktural"
     delete 'struktural/:id' => 'functional_structurals#destroy', :as => "delete_struktural"

     #electricalshcedulesubject
     get 'download_sk_mengajar_sipil' => 'civilschedulesubjects#download_pdf', :as => "download_sk_mengajar_sipil"
     get 'download_sk_mengajar_elektro' => 'electricalschedulesubjects#download_pdf', :as => "download_sk_mengajar_elektro"

       #  surat masuk
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

       #  surat keluar
      #  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
      #  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#show', :as => "calon_mahasiswa"
      #  delete 'calon_mahasiswa/:nama' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
      #  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

    resources :registrations do
       collection do
         get 'ok' => 'registrations#ok_mahasiswa', :as => "ok_mahasiswa"
       end
    end


  end

  resources :incoming_mails, :outcoming_mails, :students_biographies, :buku_induks, :functional_structurals, :lectures, :registrations, :electrical_subjects, :civil_subjects, :studiyears, :classrooms, :classtimes, :electricalschedulesubjects, :civilschedulesubjects, :semesters, :class_times
  #registrations
  get 'calon_mahasiswa_index' => 'registrations#index', :as => "calon_mahasiswa_index"
  get 'calon_mahasiswa_index/new' => 'registrations#new', :as => "new_calon_mahasiswa"
  get 'calon_mahasiswa/:id/edit' => 'registrations#edit', :as => "edit_calon_mahasiswa"
  get 'calon_mahasiswa/:id' => 'registrations#show', :as => "calon_mahasiswa"
  delete 'calon_mahasiswa/:id' => 'registrations#destroy', :as => "delete_calon_mahasiswa"
  get 'calon_mahasiswa/:nama' => 'registrations#download_pdf', :as => "calon_mahasiswa_download_pdf"

  #lectures
  get 'dosen' => 'lectures#index', :as => "dosen"

  #surat masuk
  get 'surat_masuk_index' => 'incoming_mails#index', :as => "surat_masuk_index"

  #kurikulum Teknik Elektro
  resources :electrical_subjects do
    # collection do
    #   get  'download' => 'electrical_subjects#download', as: :download
    # end
  end
  #beranda
  root 'pages#index'
  get 'aturan_kuliah' => 'pages#aturan_kuliah', :as => 'aturan_kuliah'


  # users
  # resources :users do
  #   resources :choose_electrical_subjects
  # end

end

app/models/buku_induk.rb
# == Schema Information
#
# Table name: buku_induks
#
#  id                      :integer          not null, primary key
#  no_stambuk              :string
#  nama                    :string
#  jenis_kelamin           :string
#  tempat_lahir            :string
#  tanggal_lahir           :string
#  bangsa                  :string
#  agama                   :string
#  alamat                  :string
#  ijazah_terakhir         :string
#  nama_ayah               :string
#  nama_ibu                :string
#  nama_wali               :string
#  pekerjaan_orangtua_wali :string
#  tanggal_akademik        :string
#  status_akademik         :string
#  semester_akademik       :string
#  foto                    :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class BukuInduk < ActiveRecord::Base
  def self.search(query)
    #code
    where("lower(name) like lower(?) OR lower(no_stambuk) like lower(?)", "%#{query}%", "%#{query}%")
  end
end

app/controllers/admin/buku_induks_controller.rb
class Admin::BukuInduksController < Admin::ApplicationController
  before_action :verify_logged_in
  before_action :set_buku_induk, only: [:show, :edit, :update, :destroy]

  # GET /buku_induks
  # GET /buku_induks.json
  def index
    if params[:search]
        @buku_induks = BukuInduk.paginate(:page => params[:page], per_page: 10).search(params[:search]).order('created_at DESC')
    else
        @buku_induks = BukuInduk.all.paginate(:page => params[:page], per_page: 10).order('created_at DESC')
    end
  end

  # GET /buku_induks/1
  # GET /buku_induks/1.json
  def show
  end

  # GET /buku_induks/new
  def new
    @buku_induk = BukuInduk.new
  end

  # GET /buku_induks/1/edit
  def edit
  end

  # POST /buku_induks
  # POST /buku_induks.json
  def create
    @buku_induk = BukuInduk.new(buku_induk_params)

    respond_to do |format|
      if @buku_induk.save
        format.html { redirect_to admin_buku_induks_path, notice: 'Data Berhasil Dibuat.' }
        format.json { render :show, status: :created, location: @buku_induk }
      else
        format.html { render :new }
        format.json { render json: @buku_induk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buku_induks/1
  # PATCH/PUT /buku_induks/1.json
  def update
    respond_to do |format|
      if @buku_induk.update(buku_induk_params)
        format.html { redirect_to admin_buku_induks_path, notice: 'Data Berhasil Di Update.' }
        format.json { render :show, status: :ok, location: @buku_induk }
      else
        format.html { render :edit }
        format.json { render json: @buku_induk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buku_induks/1
  # DELETE /buku_induks/1.json
  def destroy
    @buku_induk.destroy
    respond_to do |format|
      format.html { redirect_to admin_buku_induks_url, notice: 'Buku induk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buku_induk
      @buku_induk = BukuInduk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buku_induk_params
      params.require(:buku_induk).permit(:no_stambuk, :nama, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :bangsa, :agama, :alamat, :ijazah_terakhir, :nama_ayah, :nama_ibu, :nama_wali, :pekerjaan_orangtua_wali, :tanggal_akademik, :status_akademik, :semester_akademik, :foto)
    end
end

app/controllers/buku_induks_controller.rb
class BukuInduksController < ApplicationController
  before_action :set_buku_induk, only: [:show]

  # GET /buku_induks
  # GET /buku_induks.json
  def index
    @buku_induks = BukuInduk.all
  end

  # GET /buku_induks/1
  # GET /buku_induks/1.json
  def show
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buku_induk
      @buku_induk = BukuInduk.find(params[:id])
    end
end

app/helpers/buku_induks_helper.rb
module BukuInduksHelper
end

app/views/admin/buku_induks/_form.html.erb
<%= simple_form_for([:admin, @buku_induk], wrapper: :horizontal_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :no_stambuk %>
    <%= f.input :nama %>
    <%= f.input :jenis_kelamin %>
    <%= f.input :tempat_lahir %>
    <%= f.input :tanggal_lahir %>
    <%= f.input :bangsa %>
    <%= f.input :agama %>
    <%= f.input :alamat %>
    <%= f.input :ijazah_terakhir %>
    <%= f.input :nama_ayah %>
    <%= f.input :nama_ibu %>
    <%= f.input :nama_wali %>
    <%= f.input :pekerjaan_orangtua_wali %>
    <%= f.input :tanggal_akademik %>
    <%= f.input :status_akademik %>
    <%= f.input :semester_akademik %>
    <%= f.input :foto %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/buku_induks/edit.html.erb
<h3 class="lead">Edit Buku Induk</h3>

<%= render 'form' %>

<%= link_to 'Lihat', admin_buku_induk_path(@buku_induk) %> |
<%= link_to 'Kembali', admin_buku_induks_path %>

app/views/admin/buku_induks/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="well">
      <h3 class="lead">Daftar Buku Induk &nbsp;&nbsp;<%= link_to 'Buat', new_admin_buku_induk_path, class: "btn btn-success" %></h3>

      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Stambuk</th>
            <th>Nama</th>
            <th>Jenis kelamin</th>
            <th>Tempat, Tanggal Lahir</th>
            <th>Tanggal akademik</th>
            <th>Status akademik</th>
            <th>Semester akademik</th>
            <th>Foto</th>
            <th colspan='1'></th>
          </tr>
        </thead>

        <tbody>
          <% @buku_induks.each do |buku_induk| %>
            <tr>
              <td><%= link_to buku_induk.no_stambuk, buku_induk %></td>
              <td><%= buku_induk.nama %></td>
              <td><%= buku_induk.jenis_kelamin %></td>
              <td><%= buku_induk.tempat_lahir %>&nbsp;&nbsp;&nbsp;<%= buku_induk.tanggal_lahir %></td>
              <td><%= buku_induk.tanggal_akademik %></td>
              <td><%= buku_induk.status_akademik %></td>
              <td><%= buku_induk.semester_akademik %></td>
              <td><%= buku_induk.foto %></td>
              <td><%= link_to 'Edit', edit_admin_buku_induk_path(buku_induk), class:'btn btn-warning' %>&nbsp;&nbsp;<%= link_to 'Hapus', admin_buku_induk_path(buku_induk), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>




    </div>
  </div>
</div>

app/views/admin/buku_induks/new.html.erb
<h3 class="lead">Buat Buku Induk Baru</h1>

<%= render 'form' %>
<br>
<%= link_to 'Kembali', admin_buku_induks_path, class: "btn btn-success" %>

app/views/admin/buku_induks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No stambuk:</strong>
  <%= @buku_induk.no_stambuk %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @buku_induk.nama %>
</p>

<p>
  <strong>Jenis kelamin:</strong>
  <%= @buku_induk.jenis_kelamin %>
</p>

<p>
  <strong>Tempat lahir:</strong>
  <%= @buku_induk.tempat_lahir %>
</p>

<p>
  <strong>Tanggal lahir:</strong>
  <%= @buku_induk.tanggal_lahir %>
</p>

<p>
  <strong>Bangsa:</strong>
  <%= @buku_induk.bangsa %>
</p>

<p>
  <strong>Agama:</strong>
  <%= @buku_induk.agama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @buku_induk.alamat %>
</p>

<p>
  <strong>Ijazah terakhir:</strong>
  <%= @buku_induk.ijazah_terakhir %>
</p>

<p>
  <strong>Nama ayah:</strong>
  <%= @buku_induk.nama_ayah %>
</p>

<p>
  <strong>Nama ibu:</strong>
  <%= @buku_induk.nama_ibu %>
</p>

<p>
  <strong>Nama wali:</strong>
  <%= @buku_induk.nama_wali %>
</p>

<p>
  <strong>Pekerjaan orangtua wali:</strong>
  <%= @buku_induk.pekerjaan_orangtua_wali %>
</p>

<p>
  <strong>Tanggal akademik:</strong>
  <%= @buku_induk.tanggal_akademik %>
</p>

<p>
  <strong>Status akademik:</strong>
  <%= @buku_induk.status_akademik %>
</p>

<p>
  <strong>Semester akademik:</strong>
  <%= @buku_induk.semester_akademik %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @buku_induk.foto %>
</p>

<%= link_to 'Edit', edit_buku_induk_path(@buku_induk) %> |
<%= link_to 'Back', buku_induks_path %>